version: '3'
# ecs-params file is required to upload to AWS
services:
  app:
    image: '$TAGGED_IMAGE'
    expose:
      - '5000'
    environment:
      NODE_ENV: production
    restart: always
  proxy:
    image: '$TAGGED_IMAGE_PROXY'
    ports:
      - '80:80'
      - '443:443'
    restart: always